# Generated by Django 5.2.7 on 2025-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_paragraph', models.TextField(help_text='The opening paragraph of the About section.', verbose_name='First Paragraph')),
                ('second_paragraph', models.TextField(help_text='The follow-up paragraph of the About section.', verbose_name='Second Paragraph')),
                ('clients_number', models.PositiveIntegerField(default=0, help_text='The total number of clients served.', verbose_name='Clients Number')),
                ('vessels_number', models.PositiveIntegerField(default=0, help_text='The total number of vessels listed or brokered.', verbose_name='Vessels Number')),
                ('deals_number', models.PositiveIntegerField(default=0, help_text='The total number of successful deals closed.', verbose_name='Deals Number')),
            ],
            options={
                'verbose_name': 'About Section & Stats',
                'verbose_name_plural': 'About Section & Stats',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The main headline for the website's hero section.", max_length=255, verbose_name='Headline (H1)')),
                ('subtitle', models.TextField(help_text='The descriptive paragraph below the main headline.', verbose_name='Subtext (P)')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a photo of the vessel. (e.g., cargo-vessel.avif)', upload_to='ships/', verbose_name='Ship Image')),
                ('title', models.CharField(help_text='e.g., Cargo Vessels, Chemical Tanker, Offshore Rig', max_length=100, verbose_name='Vessel Type/Title')),
                ('subtitle', models.CharField(help_text='e.g., 2010 built • 52k DWT • prompt delivery', max_length=200, verbose_name='Card Description')),
                ('is_featured', models.BooleanField(default=False, help_text='If checked, this ship may be included in the homepage carousel.', verbose_name='Show in Carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ship Listing',
                'verbose_name_plural': 'Ship Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_paragraph', models.TextField(help_text="The introductory text that appears under 'Ships for Sale'.", verbose_name='Section Subtitle Paragraph')),
            ],
            options={
                'verbose_name': 'Ships Section Intro',
                'verbose_name_plural': 'Ships Section Intro',
            },
        ),
    ]
