# Generated by Django 5.2.7 on 2025-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text="The company's full physical address.", verbose_name='Physical Address')),
                ('phone', models.CharField(help_text='The primary contact phone number.', max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='The primary contact email address.', max_length=254, verbose_name='Email Address')),
                ('open_time_1', models.CharField(help_text="e.g., 'Monday - Friday: 9:00 - 17:00'", max_length=100, verbose_name='Opening Time Line 1')),
                ('open_time_2', models.CharField(help_text="e.g., 'Saturday: 10:00 - 14:00' or similar details.", max_length=100, verbose_name='Opening Time Line 2')),
                ('open_time_3', models.CharField(help_text="Additional day/time details (e.g., 'Sunday: Closed').", max_length=100, verbose_name='Opening Time Line 3')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Facebook, LinkedIn, WhatsApp', max_length=50, verbose_name='Platform Name')),
                ('icon_class', models.CharField(help_text="e.g., 'fa-brands fa-facebook-f' or 'fa-brands fa-whatsapp'. Use this for awesome fonts icon.", max_length=50, verbose_name='Font Awesome Icon Class')),
                ('url', models.URLField(help_text='The full URL for the social media profile.', verbose_name='Link URL')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
