# Generated by Django 5.2.7 on 2025-10-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactsection_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Social Links', 'verbose_name_plural': 'Social Links'},
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='url',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='fb_link',
            field=models.URLField(blank=True, help_text='Full URL to your Facebook page/profile.', verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='insta_link',
            field=models.URLField(blank=True, help_text='Full URL to your Instagram profile.', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='linkedin_link',
            field=models.URLField(blank=True, help_text='Full URL to your LinkedIn profile.', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Full URL to your WhatsApp chat link (e.g., https://wa.me/123456789).', verbose_name='WhatsApp URL'),
        ),
    ]
