# Generated by Django 5.2.7 on 2025-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sociallink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If checked, this ship will be included in the homepage carousel.', verbose_name='Feature this Ship'),
        ),
    ]
